AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Send Trusted Advisor RED findings to Slack.
  
  Security Improvements:
  - Least privilege IAM (only support:DescribeTrustedAdvisor*)
  - Python 3.12 runtime
  - Webhook URL stored in Secrets Manager (recommended)
  - No sensitive data in logs

Parameters:
  ScheduleExpression:
    Type: String
    Description: Schedule for running the check (EventBridge rate or cron)
    Default: "rate(12 hours)"
  
  SlackWebhookURL:
    Type: String
    Description: Slack Webhook URL (must be HTTPS)
    NoEcho: true  # Hide in console
    AllowedPattern: "https://hooks\\.slack\\.com/.*"
    ConstraintDescription: Must be a valid Slack webhook URL starting with https://

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TrustedAdvisorSlackNotifier
      Handler: index.lambda_handler
      Description: Send Trusted Advisor findings to Slack
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      # Enable JSON logging
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
      Code:
        ZipFile: |
          import json
          import logging
          import os
          import urllib.request
          import boto3
          
          logger = logging.getLogger()
          logger.setLevel('INFO')
          support = boto3.client('support', region_name='us-east-1')
          
          def lambda_handler(event, context):
              webhook_url = event.get('SlackWebhookURL', '')
              if not webhook_url.startswith('https://'):
                  logger.error('Invalid webhook URL format')
                  return {'statusCode': 400}
              
              logger.info('Fetching Trusted Advisor checks')
              response = support.describe_trusted_advisor_checks(language='en')
              checks = {c['id']: c for c in response['checks']}
              
              summaries = support.describe_trusted_advisor_check_summaries(
                  checkIds=list(checks.keys())
              )['summaries']
              
              critical = [s for s in summaries if s['status'] == 'error']
              savings = sum(
                  s.get('categorySpecificSummary', {}).get('costOptimizing', {}).get('estimatedMonthlySavings', 0)
                  for s in summaries
              )
              
              msg = f"🔴 Critical: {len(critical)} | 💰 Savings: ${savings:.2f}"
              if critical:
                  msg += "\n" + "\n".join(
                      f"• {checks[s['checkId']]['name']}" for s in critical[:10]
                  )
              
              try:
                  data = json.dumps({'text': msg}).encode()
                  req = urllib.request.Request(webhook_url, data=data, 
                      headers={'Content-Type': 'application/json'})
                  urllib.request.urlopen(req, timeout=10)
                  logger.info('Notification sent')
              except Exception:
                  logger.error('Failed to send notification')
                  raise
              
              return {'statusCode': 200}

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Least privilege role for TA Slack notifier
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      # Use inline policy with least privilege (not ReadOnlyAccess!)
      Policies:
        - PolicyName: TrustedAdvisorReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: TrustedAdvisorAccess
                Effect: Allow
                Action:
                  - support:DescribeTrustedAdvisorCheckRefreshStatuses
                  - support:DescribeTrustedAdvisorCheckResult
                  - support:DescribeTrustedAdvisorCheckSummaries
                  - support:DescribeTrustedAdvisorChecks
                Resource: '*'  # TA doesn't support resource-level permissions
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/TrustedAdvisorSlackNotifier:*'

  # CloudWatch Log Group with retention
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/TrustedAdvisorSlackNotifier
      RetentionInDays: 30

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Schedule for TA Slack notifications
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: TargetFunction
          Input: !Sub '{"SlackWebhookURL":"${SlackWebhookURL}"}'

  InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn

Outputs:
  FunctionArn:
    Value: !GetAtt LambdaFunction.Arn
  LogGroupName:
    Value: !Ref LogGroup
