AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Enable S3 bucket versioning based on Trusted Advisor checks.
  
  Security Features:
  - Least privilege IAM with account scope
  - Tag-based exclusion
  - Structured JSON logging
  - Dead Letter Queue
  - CloudWatch alarm

Globals:
  Function:
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: WARN

Parameters:
  ExcludeTag:
    Type: String
    Default: 'DisableVersioning'
    Description: Tag key that excludes bucket from versioning

Resources:
  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TAS3Versioning-DLQ
      MessageRetentionPeriod: 1209600
      KmsMasterKeyId: alias/aws/sqs

  EnableVersioningFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TA-EnableS3Versioning
      Description: Enables S3 bucket versioning unless excluded by tag
      CodeUri: ./lambda/
      Handler: app.lambda_handler
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DLQ.Arn
      Environment:
        Variables:
          EXCLUDE_TAG: !Ref ExcludeTag
          LOG_LEVEL: INFO
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: S3Versioning
              Effect: Allow
              Action:
                - s3:PutBucketVersioning
                - s3:GetBucketTagging
              Resource: !Sub 'arn:aws:s3:::*'
              Condition:
                StringEquals:
                  s3:ResourceAccount: !Ref AWS::AccountId
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DLQ.QueueName
      Events:
        TrustedAdvisorEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.trustedadvisor
              detail-type:
                - Trusted Advisor Check Item Refresh Notification
              detail:
                status:
                  - WARN
                check-name:
                  - Amazon S3 Bucket Versioning
            State: ENABLED

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: TAS3Versioning-Errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EnableVersioningFunction

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${EnableVersioningFunction}'
      RetentionInDays: 30

Outputs:
  FunctionArn:
    Value: !GetAtt EnableVersioningFunction.Arn
  DLQUrl:
    Value: !Ref DLQ
